version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: service-sql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ./db-mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - my_network

  web:
    image: carlosdevresearch/web-rag-chatbot:01  # Use the pre-built image
    container_name: web-service
    volumes:
      - ./data:/App/data
    ports:
      - "5000:5000"
    networks:
      - my_network
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: all
              capabilities: [gpu]

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf  # Nginx configuration file
      - ./reverse-proxy/certs:/etc/nginx/certs            # SSL certificates
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS
    networks:
      - my_network
    depends_on:
      - web   # Ensure Nginx starts after the web service

networks:
  my_network:
    driver: bridge
